import { Message } from "node-telegram-bot-api";
import {
  generateSecretKey,
  generateWallet,
  generateNewAccount,
  restoreWalletAccounts,
} from "@stacks/wallet-sdk";
import { StacksMainnet } from "@stacks/network";
import { bot } from "../bot/bot";

interface Wallet {
  /** Used when generating app private keys, which encrypt app-specific data */
  salt: string;
  /** The private key associated with the root of a BIP39 keychain */
  rootKey: string;
  /** A private key used to encrypt configuration data */
  configPrivateKey: string;
  /** The encrypted secret key */
  encryptedSecretKey: string;
  /** A list of accounts generated by this wallet */
  accounts: Account[];
}

interface Account {
  /** The private key used for STX payments */
  stxPrivateKey: string;
  /** The private key used in Stacks 1.0 to register BNS names */
  dataPrivateKey: string;
  /** The salt is the same as the wallet-level salt. Used for app-specific keys */
  salt: string;
  /** A single username registered via BNS for this account */
  username?: string;
  /** A profile object that is publicly associated with this account's username */
  //profile?: Profile;
  /** The root of the keychain used to generate app-specific keys */
  appsKey: string;
  /** The index of this account in the user's wallet. Zero-indexed */
  index: number;
}

//export const handleCreateWallet = (msg: Message) => {
//  const chatId = msg.chat.id;

//  return bot.sendMessage(
//    chatId,
//    "Okay we are setting up a new wallet for you.."
//  );
//};

export const handleCreateWallet = async (msg: Message) => {
  const chatId = msg.chat.id;

  /**
   * to generate a wallet for the user we need to ask them for a pass to be
    linked to the wallet
   */

  const password = "password"; // this should be the password the user provides

  /* to generate a new secret key for the user.
  without passing any param to the `generateSecretKey` function, it will
  generate a 24-word secret key and passing 128 as a param will generate a
  12-word secret key
  */
  const secretKey = generateSecretKey(128);

  // create a wallet object
  const wallet = await generateWallet({ secretKey, password });

  console.log(wallet);

  return bot.sendMessage(
    chatId,
    "Okay we are setting up a new wallet for you..",
  );
};

export const handleAddAccount = async (msg: Message) => {
  // in stacks, after the first wallet have been created users can choose to add accounts this is done to diversify the assets.
  // we should find a way to get the user wallet object here, or merge this function with `handleCreateWallet`
  //wallet = await generateNewAccount(wallet); // adds a new account to an existing wallet object, immutable, NOT in-place
};

// export const handleAddExistingWallet = async (msg: Message) => {
//   const chatId = msg.chat.id;
//
//   const restoreWallet = await restoreWalletAccounts({
//     // `baseWallet` is returned from `generateWallet`
//     // Users can host their own Gaia hub, and this library's API can use that Gaia hub, if provided.
//     // i dont understand what they mean by the above 🥺
//     wallet: baseWallet,
//     gaiaHubUrl: "https://hub.blockstack.org",
//     network: new StacksMainnet(),
//   });
//
//   return bot.sendMessage(
//     chatId,
//     "Okay we are adding a new wallet for you now. ",
//   );
// };
