import { Message } from "node-telegram-bot-api";
import { bot } from "../bot";
import { generateSecretKey, generateWallet } from "@stacks/wallet-sdk";

interface Wallet {
  /** Used when generating app private keys, which encrypt app-specific data */
  salt: string;
  /** The private key associated with the root of a BIP39 keychain */
  rootKey: string;
  /** A private key used to encrypt configuration data */
  configPrivateKey: string;
  /** The encrypted secret key */
  encryptedSecretKey: string;
  /** A list of accounts generated by this wallet */
  //accounts: Account[];  i haven't figured this out
}

export const startCommand = (msg: Message) => {
  const chatId = msg.chat.id;

  return bot.sendMessage(chatId, "Welcome to Mecury ", {
    reply_markup: {
      inline_keyboard: [
        [
          {
            text: "🚀 Create a New Wallet",
            callback_data: JSON.stringify({ command: "create" }),
          },
        ],
        [
          {
            text: "💼 Add an Existing Wallet",
            callback_data: JSON.stringify({ command: "add" }),
          },
        ],
        [{ text: "🔍 Learn More", url: "https://www.linkbarn.tech" }],
      ],
    },
  });
};

//export const handleCreateWallet = (msg: Message) => {
//  const chatId = msg.chat.id;

//  return bot.sendMessage(
//    chatId,
//    "Okay we are setting up a new wallet for you.."
//  );
//};

export const handleCreateWallet = (msg: Message) => {
  const chatId = msg.chat.id;

  /**
   * to generate a wallet for the user we need to ask them for a pass to be
    linked to the wallet
   */

  const password = "password"; // this should be the password the user provides

  /* to generate a new secret key for the user.
  without passing any param to the `generateSecretKey` function, it will
  generate a 24-word secret key and passing 128 as a param will generate a
  12-word secret key
  */
  const secretKey = generateSecretKey(128);

  const wallet = generateWallet({ secretKey, password });

  return bot.sendMessage(
    chatId,
    "Okay we are setting up a new wallet for you.."
  );
};

export const handleAddExistingWallet = (msg: Message) => {
  const chatId = msg.chat.id;

  return bot.sendMessage(
    chatId,
    "Okay we are adding a new wallet for you now. "
  );
};
